### ISSUE TITLE
just letting you know about this archiver

### ISSUE THREAD

**Issue by pokeball99** [HenrySlawniak/4chan-thread-archiver#1]
https://github.com/bibanon/BASC-Archiver
(keep up the work,it could end up being better than what they did..maybe)

**Comment by HenrySlawniak** [comment]
Haha I've seen that, I just really don't like Python, and want to write some more Go.

**Comment by pokeball99** [comment]
well, when you are making this,could you pleases follow these specs for the output: https://github.com/bibanon/chan.arc (or you could just be special/non-interchangeable :\ )
